# Generated by Django 4.0.3 on 2023-05-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_remove_doctor_institute_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultationform',
            fields=[
                ('consult_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=30)),
                ('department', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=50)),
                ('time', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
