# Generated by Django 4.0.3 on 2023-05-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_consultationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationform',
            name='consult_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
